version: 1
disable_existing_loggers: False

formatters:
  default:
    format: '%(asctime)s - %(name)s -%(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  json:
    format: '{"timestamp": "%(asctime)s", "logger": "%(name)s", "level": "%(levelname)s", "message": "%(message)s"}'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: INFO
    formatter: json
    filename: app.log
    mode: a

loggers:
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: no

  app:
    level: DEBUG
    handlers: [console, file]
    propagate: no
