"""empty message

Revision ID: 4c5265a489d4
Revises: 8059ff2ccbcc
Create Date: 2025-09-23 20:01:38.453908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c5265a489d4'
down_revision: Union[str, Sequence[str], None] = '8059ff2ccbcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('allow_comments', sa.Boolean(), nullable=False))
    op.drop_column('posts', 'allow_comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('allow_comment', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('posts', 'allow_comments')
    # ### end Alembic commands ###
